name: Run checks in pr

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: dart format --set-exit-if-changed --line-length 120 .

      - run: flutter analyze --no-fatal-infos
